#define _GNU_SOURCE
#define _POSIX_C_SOURCE 200809L

#include <vdp.h>
#include <kbd_sim_internal.h>

#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <X11/XKBlib.h>
#include <errno.h>
#include <pthread.h>
#include <signal.h>
#include <stdatomic.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <time.h>
#include <unistd.h>

/* ================================================================
 * Memory sizes: match the Verilog/BRAM layout.
 * ================================================================ */

#define R0_SIZE 0x00002000u /* Verilog R0 MEM_SIZE = 8192 bytes */
#define B0_SIZE 0x00800000u
#define T0_MAP_SIZE 0x00008000u
#define T0_DATA_SIZE 0x00010000u
#define T1_MAP_SIZE 0x00008000u
#define T1_DATA_SIZE 0x00010000u
#define S0_ATT_SIZE 0x00000200u
#define S0_DATA_SIZE 0x00008000u

#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 480

#define TILE_MAP_WIDTH 128
#define TILE_MAP_HEIGHT 128
#define TILE_WIDTH 8
#define TILE_HEIGHT 8
#define TILE_COUNT 1024

#define SPRITE_COUNT 64
#define MAX_SPR_LINE 32
#define SPR_DATA_WORDS 2048 /* 128-bit words, 16 bytes each */

/* ================================================================
 * R0 word addresses from REG_MEMORY.
 * r0 is uint32_t*, therefore these are 32-bit word indices.
 * ================================================================ */

#define REG_CTRL_0 0x000u
#define REG_STAT_0 0x001u
#define REG_LINE 0x002u
#define REG_BCK_GND 0x003u
#define REG_T0_X_OFF 0x004u
#define REG_T0_Y_OFF 0x005u
#define REG_T1_X_OFF 0x008u
#define REG_T1_Y_OFF 0x009u
#define REG_B0_X_OFF 0x00Cu
#define REG_B0_Y_OFF 0x00Du

#define PAL_T0_ADDR 0x100u
#define PAL_T1_ADDR 0x200u
#define PAL_S0_ADDR 0x300u

#define BIT_STAT_H_BLANK 0
#define BIT_STAT_V_BLANK 1

#define BIT_CTRL_T0_EN 0
#define BIT_CTRL_T1_EN 1
#define BIT_CTRL_S0_EN 2
#define BIT_CTRL_B0_EN 3
#define BIT_CTRL_B0_LINUX_CMP 4

/* ================================================================
 * Public memory pointers.  These are the only symbols main needs.
 * ================================================================ */

volatile uint32_t *r0 = NULL;
volatile uint16_t *b0 = NULL;
volatile uint16_t *t0_map = NULL;
volatile uint8_t *t0_data = NULL;
volatile uint16_t *t1_map = NULL;
volatile uint8_t *t1_data = NULL;
volatile uint64_t *s0_att = NULL;
volatile uint8_t *s0_data = NULL;

/* ================================================================
 * Internal simulator state.
 * ================================================================ */

static pthread_t sim_thread;
static int sim_thread_created = 0;
static _Atomic int sim_running = 0;

/* One ARGB4444 line, as generated by the sprite block. */
static uint16_t sprite_line[SCREEN_WIDTH];

/* Final RGB444 image before conversion to the host X11 visual. */
static uint16_t final_frame[SCREEN_WIDTH * SCREEN_HEIGHT];

static const uint16_t basic_palette[16] = {
    0x0000, 0xF000, 0xFFFF, 0xFF00,
    0xF0F0, 0xF00F, 0xFFF0, 0xFF0F,
    0xF0FF, 0xF800, 0xF080, 0xF008,
    0xF880, 0xF808, 0xF088, 0xF888};

static void *map_zeroed(size_t size)
{
    void *p = mmap(NULL, size,
                   PROT_READ | PROT_WRITE,
                   MAP_PRIVATE | MAP_ANONYMOUS,
                   -1, 0);

    if (p == MAP_FAILED)
        return NULL;

    memset(p, 0, size);
    return p;
}

static void unmap_region(volatile void **p, size_t size)
{
    if (*p != NULL)
    {
        munmap((void *)*p, size);
        *p = NULL;
    }
}

static int allocate_vdp_memory(void)
{
    r0 = (volatile uint32_t *)map_zeroed(R0_SIZE);
    b0 = (volatile uint16_t *)map_zeroed(B0_SIZE);
    t0_map = (volatile uint16_t *)map_zeroed(T0_MAP_SIZE);
    t0_data = (volatile uint8_t *)map_zeroed(T0_DATA_SIZE);
    t1_map = (volatile uint16_t *)map_zeroed(T1_MAP_SIZE);
    t1_data = (volatile uint8_t *)map_zeroed(T1_DATA_SIZE);
    s0_att = (volatile uint64_t *)map_zeroed(S0_ATT_SIZE);
    s0_data = (volatile uint8_t *)map_zeroed(S0_DATA_SIZE);

    if (!r0 || !b0 || !t0_map || !t0_data ||
        !t1_map || !t1_data || !s0_att || !s0_data)
        return -1;

    return 0;
}

static void free_vdp_memory(void)
{
    unmap_region((volatile void **)&s0_data, S0_DATA_SIZE);
    unmap_region((volatile void **)&s0_att, S0_ATT_SIZE);
    unmap_region((volatile void **)&t1_data, T1_DATA_SIZE);
    unmap_region((volatile void **)&t1_map, T1_MAP_SIZE);
    unmap_region((volatile void **)&t0_data, T0_DATA_SIZE);
    unmap_region((volatile void **)&t0_map, T0_MAP_SIZE);
    unmap_region((volatile void **)&b0, B0_SIZE);
    unmap_region((volatile void **)&r0, R0_SIZE);
}

static void initialize_r0_defaults(void)
{
    unsigned i;

    /* mmap() already gave us zeroed register space. */

    /* T0 and T1 palettes: all opaque black first. */
    for (i = 0; i < 256; ++i)
    {
        r0[PAL_T0_ADDR + i] = 0xF000;
        r0[PAL_T1_ADDR + i] = 0xF000;
    }

    for (i = 0; i < 16; ++i)
    {
        r0[PAL_T0_ADDR + i] = basic_palette[i];
        r0[PAL_T1_ADDR + i] = basic_palette[i];
    }

    /* Four 256-entry sprite palettes. */
    for (i = 0; i < 1024; ++i)
        r0[PAL_S0_ADDR + i] = 0xF000;

    /* Verilog initializes only sprite palette 0 basic colors. */
    for (i = 0; i < 16; ++i)
        r0[PAL_S0_ADDR + i] = basic_palette[i];
}

static inline int argb4444_visible(uint16_t c)
{
    return (c & 0xF000u) != 0;
}

static inline uint16_t tile_pixel(volatile uint16_t *map,
                                  volatile uint8_t *data,
                                  unsigned palette_base,
                                  int x, int y,
                                  unsigned x_off,
                                  unsigned y_off)
{
    /*
     * Verilog behavior:
     *   map is 128x128
     *   tile is 8x8
     *   map entry low 10 bits = tile number
     *   tile pixel byte = palette index
     *
     * map_x is 7 bits and map_r_addr is 14 bits, so scrolling wraps at
     * 1024 pixels in both axes.
     */
    unsigned wx = (unsigned)x + (x_off & 0x3FFu);
    unsigned wy = (unsigned)y + (y_off & 0x3FFu);

    unsigned map_x = (wx >> 3) & 0x7Fu;
    unsigned map_y = (wy >> 3) & 0x7Fu;
    unsigned map_addr = (map_y << 7) | map_x;

    unsigned tile = map[map_addr] & 0x03FFu;
    unsigned px = wx & 7u;
    unsigned py = wy & 7u;

    unsigned data_addr = tile * 64u + py * 8u + px;
    uint8_t palette_index = data[data_addr];

    return (uint16_t)(r0[palette_base + palette_index] & 0xFFFFu);
}

static inline uint16_t rgb565_to_argb4444(uint16_t p)
{
    /* Exact bit selection used by VDP_bitmap_gen in linux_comp mode. */
    return (uint16_t)(0xF000u |
                      ((p >> 4) & 0x0F00u) |
                      ((p >> 3) & 0x00F0u) |
                      ((p >> 1) & 0x000Fu));
}

static inline uint16_t bitmap_pixel(int x, int y,
                                    unsigned x_off,
                                    unsigned y_off,
                                    int linux_comp)
{
    size_t index;
    uint16_t p;

    if (linux_comp)
    {
        index = (size_t)y * SCREEN_WIDTH + (size_t)x;
        p = b0[index];
        return rgb565_to_argb4444(p);
    }

    /*
     * Match Verilog exactly: one linear 640-pixel read starts at
     * ((y + y_off) * 1024 + x_off).  There is no x wrap at 1024.
     */
    index = ((size_t)((unsigned)y + (y_off & 0x3FFu)) * 1024u) +
            (x_off & 0x3FFu) + (unsigned)x;

    /* B0 is 8 MiB, so this is still safely within the simulated region
       for all register values used by the current 640x480 design. */
    return b0[index];
}

static void generate_sprite_line(int y)
{
    unsigned att_index;
    unsigned sprites_on_line = 0;

    memset(sprite_line, 0, sizeof(sprite_line));

    for (att_index = 0; att_index < SPRITE_COUNT; ++att_index)
    {
        uint64_t a = s0_att[att_index];

        unsigned x_pos = (unsigned)((a >> 0) & 0x03FFu);
        unsigned y_pos = (unsigned)((a >> 16) & 0x03FFu);
        unsigned offset = (unsigned)((a >> 36) & 0x07FFu);
        unsigned pall_num = (unsigned)((a >> 48) & 0x0003u);
        unsigned h_flip = (unsigned)((a >> 50) & 0x0001u);
        unsigned v_flip = (unsigned)((a >> 51) & 0x0001u);
        unsigned size = (unsigned)((a >> 52) & 0x0001u);
        /* Bits 54:53 (scale) are intentionally unused in the Verilog. */
        unsigned active = (unsigned)((a >> 63) & 0x0001u);

        unsigned width = size ? 32u : 16u;
        unsigned height = width;
        unsigned row;
        unsigned dx;
        unsigned base_word;

        if (!active)
            continue;

        if ((unsigned)y < y_pos || (unsigned)y >= y_pos + height)
            continue;

        /* Hardware stops after 32 active/intersecting sprites on a line. */
        if (sprites_on_line >= MAX_SPR_LINE)
            break;
        ++sprites_on_line;

        row = (unsigned)y - y_pos;
        if (v_flip)
            row = height - 1u - row;

        base_word = offset + (size ? (row << 1) : row);

        for (dx = 0; dx < width; ++dx)
        {
            unsigned src_x = h_flip ? (width - 1u - dx) : dx;
            unsigned word_addr = base_word + (src_x >> 4);
            unsigned byte_in_word = src_x & 15u;
            uint8_t palette_index;
            uint16_t color;
            unsigned screen_x = x_pos + dx;

            /* spr_data_vdp_addr is 11 bits. */
            word_addr &= (SPR_DATA_WORDS - 1u);

            palette_index = s0_data[word_addr * 16u + byte_in_word];
            color = (uint16_t)(r0[PAL_S0_ADDR +
                                  (pall_num << 8) + palette_index] &
                               0xFFFFu);

            if (!argb4444_visible(color))
                continue;

            if (screen_x < SCREEN_WIDTH)
            {
                /* Later attribute entries overwrite earlier ones, matching
                   the sequential sprite line-buffer writes. */
                sprite_line[screen_x] = color;
            }
        }
    }
}

static void render_frame(void)
{
    uint32_t ctrl = r0[REG_CTRL_0];
    unsigned t0_x_off = r0[REG_T0_X_OFF] & 0x3FFu;
    unsigned t0_y_off = r0[REG_T0_Y_OFF] & 0x3FFu;
    unsigned t1_x_off = r0[REG_T1_X_OFF] & 0x3FFu;
    unsigned t1_y_off = r0[REG_T1_Y_OFF] & 0x3FFu;
    unsigned b0_x_off = r0[REG_B0_X_OFF] & 0x3FFu;
    unsigned b0_y_off = r0[REG_B0_Y_OFF] & 0x3FFu;
    uint16_t background = (uint16_t)(r0[REG_BCK_GND] & 0x0FFFu);

    int t0_en = (ctrl >> BIT_CTRL_T0_EN) & 1u;
    int t1_en = (ctrl >> BIT_CTRL_T1_EN) & 1u;
    int s0_en = (ctrl >> BIT_CTRL_S0_EN) & 1u;
    int b0_en = (ctrl >> BIT_CTRL_B0_EN) & 1u;
    int b0_linux_comp = (ctrl >> BIT_CTRL_B0_LINUX_CMP) & 1u;

    int y;

    for (y = 0; y < SCREEN_HEIGHT; ++y)
    {
        int x;

        /* Approximate the live line/status registers while rendering. */
        r0[REG_STAT_0] = 0;
        r0[REG_LINE] = (uint32_t)(y - 1);

        if (s0_en)
            generate_sprite_line(y);
        else
            memset(sprite_line, 0, sizeof(sprite_line));

        for (x = 0; x < SCREEN_WIDTH; ++x)
        {
            uint16_t c_t1 = 0;
            uint16_t c_s0 = sprite_line[x];
            uint16_t c_t0 = 0;
            uint16_t c_b0 = 0;
            uint16_t out;

            if (t1_en)
                c_t1 = tile_pixel(t1_map, t1_data, PAL_T1_ADDR,
                                  x, y, t1_x_off, t1_y_off);

            if (t0_en)
                c_t0 = tile_pixel(t0_map, t0_data, PAL_T0_ADDR,
                                  x, y, t0_x_off, t0_y_off);

            if (b0_en)
                c_b0 = bitmap_pixel(x, y,
                                    b0_x_off, b0_y_off,
                                    b0_linux_comp);

            /* Exact final compositor priority from the Verilog:
               T1 > S0 > T0 > B0 > background. */
            if (t1_en && argb4444_visible(c_t1))
                out = c_t1;
            else if (s0_en && argb4444_visible(c_s0))
                out = c_s0;
            else if (t0_en && argb4444_visible(c_t0))
                out = c_t0;
            else if (b0_en && argb4444_visible(c_b0))
                out = c_b0;
            else
                out = background;

            final_frame[(size_t)y * SCREEN_WIDTH + x] = out & 0x0FFFu;
        }
    }

    /* We are between frames now. */
    r0[REG_STAT_0] = (1u << BIT_STAT_H_BLANK) |
                     (1u << BIT_STAT_V_BLANK);
}

static unsigned mask_shift(unsigned long mask)
{
    unsigned shift = 0;

    if (mask == 0)
        return 0;

    while ((mask & 1ul) == 0)
    {
        mask >>= 1;
        ++shift;
    }

    return shift;
}

static unsigned long component_to_mask(unsigned v8, unsigned long mask)
{
    unsigned shift;
    unsigned long maxv;

    if (mask == 0)
        return 0;

    shift = mask_shift(mask);
    maxv = mask >> shift;

    return (((unsigned long)v8 * maxv + 127ul) / 255ul) << shift;
}

static unsigned long rgb444_to_xpixel(uint16_t rgb444, Visual *visual)
{
    unsigned r8 = ((rgb444 >> 8) & 0xFu) * 17u;
    unsigned g8 = ((rgb444 >> 4) & 0xFu) * 17u;
    unsigned b8 = ((rgb444 >> 0) & 0xFu) * 17u;

    return component_to_mask(r8, visual->red_mask) |
           component_to_mask(g8, visual->green_mask) |
           component_to_mask(b8, visual->blue_mask);
}

static int host_is_little_endian(void)
{
    const uint16_t x = 1;
    return *(const uint8_t *)&x == 1;
}

static void copy_frame_to_ximage(XImage *image,
                                 Visual *visual,
                                 unsigned long xcolors[4096])
{
    int y;
    int native_order = (host_is_little_endian() && image->byte_order == LSBFirst) ||
                       (!host_is_little_endian() && image->byte_order == MSBFirst);

    (void)visual;

    if (image->bits_per_pixel == 32 && native_order)
    {
        for (y = 0; y < SCREEN_HEIGHT; ++y)
        {
            uint32_t *dst = (uint32_t *)(void *)(image->data +
                                                 y * image->bytes_per_line);
            int x;
            for (x = 0; x < SCREEN_WIDTH; ++x)
            {
                uint16_t rgb444 = final_frame[(size_t)y * SCREEN_WIDTH + x];
                dst[x] = (uint32_t)xcolors[rgb444 & 0x0FFFu];
            }
        }
    }
    else
    {
        /* Portable fallback for unusual X visuals. */
        for (y = 0; y < SCREEN_HEIGHT; ++y)
        {
            int x;
            for (x = 0; x < SCREEN_WIDTH; ++x)
            {
                uint16_t rgb444 = final_frame[(size_t)y * SCREEN_WIDTH + x];
                XPutPixel(image, x, y, xcolors[rgb444 & 0x0FFFu]);
            }
        }
    }
}

static uint64_t monotonic_ns(void)
{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (uint64_t)ts.tv_sec * 1000000000ull + (uint64_t)ts.tv_nsec;
}

static void sleep_until_ns(uint64_t target_ns)
{
    struct timespec ts;

    ts.tv_sec = (time_t)(target_ns / 1000000000ull);
    ts.tv_nsec = (long)(target_ns % 1000000000ull);

    while (clock_nanosleep(CLOCK_MONOTONIC, TIMER_ABSTIME, &ts, NULL) == EINTR)
        ;
}

static void *simulator_thread(void *arg)
{
    Display *dpy;
    int screen;
    Visual *visual;
    int depth;
    Window win;
    GC gc;
    Atom wm_delete;
    XSizeHints hints;
    XImage *image;
    unsigned long xcolors[4096];
    unsigned i;
    uint64_t next_frame;

    (void)arg;

    dpy = XOpenDisplay(NULL);
    if (!dpy)
    {
        fprintf(stderr,
                "ARES VDP simulator: cannot open X11 display; running headless\n");
        atomic_store(&sim_running, 0);
        return NULL;
    }

    Bool detectable_repeat = False;

    XkbSetDetectableAutoRepeat(
        dpy,
        True,
        &detectable_repeat);

    printf("X11 detectable autorepeat: %s\n",
           detectable_repeat ? "yes" : "no");

    screen = DefaultScreen(dpy);
    visual = DefaultVisual(dpy, screen);
    depth = DefaultDepth(dpy, screen);

    win = XCreateSimpleWindow(dpy,
                              RootWindow(dpy, screen),
                              0, 0,
                              SCREEN_WIDTH, SCREEN_HEIGHT,
                              0,
                              BlackPixel(dpy, screen),
                              BlackPixel(dpy, screen));

    XStoreName(dpy, win, "ARES VDP Simulator");
    XSelectInput(dpy, win, ExposureMask | KeyPressMask | KeyReleaseMask | StructureNotifyMask);

    memset(&hints, 0, sizeof(hints));
    hints.flags = PMinSize | PMaxSize;
    hints.min_width = hints.max_width = SCREEN_WIDTH;
    hints.min_height = hints.max_height = SCREEN_HEIGHT;
    XSetWMNormalHints(dpy, win, &hints);

    wm_delete = XInternAtom(dpy, "WM_DELETE_WINDOW", False);
    XSetWMProtocols(dpy, win, &wm_delete, 1);

    gc = XCreateGC(dpy, win, 0, NULL);
    XMapWindow(dpy, win);

    image = XCreateImage(dpy, visual, (unsigned)depth,
                         ZPixmap, 0, NULL,
                         SCREEN_WIDTH, SCREEN_HEIGHT,
                         32, 0);
    if (!image)
    {
        fprintf(stderr, "ARES VDP simulator: XCreateImage failed\n");
        XFreeGC(dpy, gc);
        XDestroyWindow(dpy, win);
        XCloseDisplay(dpy);
        atomic_store(&sim_running, 0);
        return NULL;
    }

    image->data = calloc(1, (size_t)image->bytes_per_line * image->height);
    if (!image->data)
    {
        fprintf(stderr, "ARES VDP simulator: image allocation failed\n");
        XDestroyImage(image);
        XFreeGC(dpy, gc);
        XDestroyWindow(dpy, win);
        XCloseDisplay(dpy);
        atomic_store(&sim_running, 0);
        return NULL;
    }

    for (i = 0; i < 4096; ++i)
        xcolors[i] = rgb444_to_xpixel((uint16_t)i, visual);

    /* 25 MHz pixel clock / (800 * 524) = about 59.637 Hz. */
    next_frame = monotonic_ns();

    while (atomic_load(&sim_running))
    {

        while (XPending(dpy))
        {
            XEvent ev;

            XNextEvent(dpy, &ev);

            switch (ev.type)
            {

            case ClientMessage:
                if ((Atom)ev.xclient.data.l[0] == wm_delete)
                    kill(getpid(), SIGTERM);
                break;

            case KeyPress:
            {
                KeySym ks;

                ks = XLookupKeysym(&ev.xkey, 0);

                /*
                 * keyboard_sim_x11_event() knows whether the key
                 * is already down:
                 *
                 * first KeyPress   -> value 1
                 * repeated press   -> value 2
                 */
                keyboard_sim_x11_event(
                    (unsigned long)ks,
                    1);

                break;
            }

            case KeyRelease:
            {
                XEvent next;

                /*
                 * ------------------------------------------------
                 * Detect old-style X11 autorepeat.
                 *
                 * Autorepeat is represented as:
                 *
                 *   KeyRelease
                 *   KeyPress
                 *
                 * with the SAME keycode and SAME timestamp.
                 *
                 * Ignore that fake KeyRelease.  The following
                 * KeyPress will then be interpreted as repeat.
                 * ------------------------------------------------
                 */
                if (XEventsQueued(dpy, QueuedAfterReading) > 0)
                {

                    XPeekEvent(dpy, &next);

                    if (next.type == KeyPress &&
                        next.xkey.keycode == ev.xkey.keycode &&
                        next.xkey.time == ev.xkey.time)
                    {

                        /*
                         * Fake release caused by autorepeat.
                         *
                         * Do NOT tell keyboard_sim that the key
                         * was released.
                         */
                        break;
                    }
                }

                /*
                 * Real physical key release.
                 */
                KeySym ks;

                ks = XLookupKeysym(&ev.xkey, 0);

                keyboard_sim_x11_event(
                    (unsigned long)ks,
                    0);

                break;
            }

            default:
                break;
            }
        }

        /*
         * Render VDP frame.
         */
        render_frame();

        copy_frame_to_ximage(
            image,
            visual,
            xcolors);

        XPutImage(
            dpy,
            win,
            gc,
            image,
            0, 0,
            0, 0,
            SCREEN_WIDTH,
            SCREEN_HEIGHT);

        XFlush(dpy);

        /*
         * ~59.637 Hz
         */
        next_frame += 16768193ull;

        uint64_t now = monotonic_ns();

        if (now > next_frame + 100000000ull)
            next_frame = now;

        sleep_until_ns(next_frame);
    }

    XDestroyImage(image); /* also frees image->data */
    XFreeGC(dpy, gc);
    XDestroyWindow(dpy, win);
    XCloseDisplay(dpy);

    return NULL;
}

int vdp_init(void)
{
    if (allocate_vdp_memory() != 0)
        return -1;

    initialize_r0_defaults();

    atomic_store(&sim_running, 1);

    if (pthread_create(&sim_thread, NULL,
                       simulator_thread, NULL) != 0)
    {
        atomic_store(&sim_running, 0);
        free_vdp_memory();
        return -1;
    }

    sim_thread_created = 1;

    return 0;
}

void vdp_close(void)
{
    atomic_store(&sim_running, 0);

    if (sim_thread_created)
    {
        pthread_join(sim_thread, NULL);
        sim_thread_created = 0;
    }

    free_vdp_memory();
}
